### ISSUE TITLE
TeamSkeet & MYLF don't show Actors

### ISSUE THREAD

**Issue by drraymond27** [PAhelper/PhoenixAdult.bundle#1976] opened 2024-11-21 12:39 UTC
**Describe the bug**
TeamSkeet & MYLF don't show Actors

**Include**
1. https://www.mylf.com/movies/gorgeous-crushes
2. https://www.teamskeet.com/movies/gorgeous-crushes
3. TeamSkeetXCamSoda - Gorgeous Crushes.mp4
4. [com.plexapp.agents.phoenixadult.log](https://github.com/user-attachments/files/17845814/com.plexapp.agents.phoenixadult.log)

**Comment by diamondpete** [comment] 2024-11-21 12:53
This should already be fixed by #1975 and is a duplicate of #1974. Please try again with the latest changes.

**Comment by diamondpete** [comment] 2024-11-21 16:31
Whatever change was made was reverted overnight, so I just made it try the original keys and then the new keys if the originals fail.

**Closed** 2024-11-22 05:42 UTC
