### ISSUE TITLE
New Sensations not matching

### ISSUE THREAD

**Issue by FLalfa1** [PAhelper/PhoenixAdult.bundle#104] opened 2019-02-26 15:52 UTC
It's quite a gamble on New Sensations to find the right entry.
What do you have to look for?

**Comment by delposibl** [comment] 2019-03-10 19:24
I think this is because they seems to have removed the public search functionality from their website that must have existed when the search file was created. Unfortunately this means that it probably has to be changed to the direct match style that @PAhelper explains the the readme. Ill give it a try ASAP

**Comment by delposibl** [comment] 2019-03-13 19:27
this should be fixed in the newest version...
- name your files: 
     - "newsensations.YY.MM.dd.actress.name"/"news.YY.MM.dd.actress.name" 
     - or search (in Fix Match..) "Newsensations - actress name" for a list of scenes by an actress (or "NewSensations - DVD Name" to bring up a list of scenes on a dvd)

**Comment by insickin** [comment] 2019-03-14 21:35
I'm guessing that the agent tries to scrape this website: www.newsensations.com the problem is that many DVD releases are missing from that site and or DVD releases that are noted on this site cant be fount by the agent (For example, I can't get "Veronica Rodriguez - Latina Squirt Goddess" (the whole DVD)
 https://www.newsensations.com/tour_ns/dvds/veronica-rodriguez---latina-squirt-goddess.html to be found by the agent)

I've found another New Sensations site with a search function witch finds all DVD releases: http://promo.newsensations.com/index.php

**Comment by kamuk90** [comment] 2019-06-10 17:33
@claygoldfinch 
please update file siteNewSensations
for best matching enter DVD name and choose Scene

> ex. **NewSensation-BOUND FOR SEX #3**

```
import PAsearchSites
import PAgenres

def search(results,encodedTitle,title,searchTitle,siteNum,lang,searchByDateActor,searchDate, searchSiteID):
    if searchSiteID != 9999:
        siteNum = searchSiteID
    try:
        # actress search
        try:
            searchString = searchTitle.replace(" ","-")
            searchResults = HTML.ElementFromURL(PAsearchSites.getSearchBaseURL(searchSiteID) + "/tour_ns/models/" + searchString + ".html")
        except:
            try:
                # Random actors have a trailing dash
                searchString = searchString + '-'
                searchResults = HTML.ElementFromURL(PAsearchSites.getSearchBaseURL(searchSiteID) + "/tour_ns/models/" + searchString + ".html")
            except:
                try:
                    searchString = searchTitle.replace(" ","")
                    searchResults = HTML.ElementFromURL(PAsearchSites.getSearchBaseURL(searchSiteID) + "/tour_ns/models/" + searchString + ".html")
                except:
                    searchString = searchTitle.replace(" ","")
                    searchInt = int(searchString)
                    searchResults = HTML.ElementFromURL(PAsearchSites.getSearchBaseURL(searchSiteID) + "/tour_ns/sets.php?id=" + searchString)
        for searchResult in searchResults.xpath('//div[contains(@class,"videoBlock")]'):
            titleNoFormatting = searchResult.xpath('.//div[contains(@class,"caption")]//h4//a')[0].text_content()
            Log("titleNoFormatting: " + titleNoFormatting)
            curID = searchResult.xpath('.//div[contains(@class,"caption")]//h4//a')[0].get('href').replace('/', '_').replace('?', '!')
            Log("curID: " + curID)
            releaseDate = parse(searchResult.xpath('.//p[2]')[0].text_content()[8:20].strip()).strftime('%Y-%m-%d')
            Log("releaseDate: " + releaseDate)
            if searchDate:
                score = 100 - Util.LevenshteinDistance(searchDate, releaseDate)
            else:
                score = 100 - Util.LevenshteinDistance(searchTitle.lower(), titleNoFormatting.lower())
            results.Append(MetadataSearchResult(id = curID + "|" + str(siteNum), name = titleNoFormatting + " [New Sensations] " + releaseDate, score = score, lang = lang))

    except:
        # search by DVD
            searchString = searchTitle.lower().replace(" ","-").replace("#","").replace("'","").replace("vol. ","").replace("volume ","")
            searchResults = HTML.ElementFromURL(PAsearchSites.getSearchBaseURL(searchSiteID) + "/tour_ns/dvds/" + searchString + ".html")
            for searchResult in searchResults.xpath('//div[@class="dvdScene"]'):
                titleNoFormatting = searchResult.xpath('.//h4//a')[0].text_content()
                Log("titleNoFormatting: " + titleNoFormatting)
                curID = searchResult.xpath('.//h4//a')[0].get('href').replace('/','_').replace('?','!')
                Log("curID: " + curID)
                releaseDate = parse(searchResult.xpath('.//div[@class="date"]')[0].text_content().split(' l ')[0].replace("Released","").strip()).strftime('%Y-%m-%d')
                Log("releaseDate: " + releaseDate)
                if searchDate:
                    score = 100 - Util.LevenshteinDistance(searchDate, releaseDate)
                else:
                    score = 100 - Util.LevenshteinDistance(searchTitle.lower(), titleNoFormatting.lower())
                results.Append(MetadataSearchResult(id = curID + "|" + str(siteNum) + "|" + releaseDate, name = titleNoFormatting + " [New Sensations] " + releaseDate, score = score, lang = lang))

# From when site had search functionality
    # searchResults = HTML.ElementFromURL(PAsearchSites.getSearchSearchURL(siteNum) + encodedTitle)
    # for searchResult in searchResults.xpath('//h4//a'):
    #     Log(str(searchResult.get('href')))
    #     titleNoFormatting = searchResult.text_content()
    #     curID = searchResult.get('href').replace('/','_').replace('?','!')
    #     score = 100 - Util.LevenshteinDistance(title.lower(), titleNoFormatting.lower())
    #
    #     results.Append(MetadataSearchResult(id = curID + "|" + str(siteNum), name = titleNoFormatting + " [New Sensations]", score = score, lang = lang))
    return results

def update(metadata,siteID,movieGenres,movieActors):

    Log("metadata.id: " + metadata.id)
    metadata.studio = 'New Sensations'
    # Scene(details) page
    detailsPageElements = HTML.ElementFromURL(str(metadata.id).split("|")[0].replace('_','/').replace('!','?').replace('tour/ns','tour_ns'))

    # Scene Title
    metadata.title = detailsPageElements.xpath('//div[@class="trailerVideos clear"]//div[@class="title clear"]//h3')[0].text_content()

    # Summary
    metadata.summary = detailsPageElements.xpath('//div[@class="trailerInfo"]//p')[0].text_content().strip()

    # DVD name
    tagline = detailsPageElements.xpath('//div[@class="trailerInfo"]//ul//li[4]//a')[0].text_content().strip()
    Log("DVD name/tagline: " + tagline)
    metadata.collections.clear()
    metadata.tagline = tagline
    metadata.collections.add(tagline)

    # DVD Page
    dvdPageLink = detailsPageElements.xpath('//div[@class="trailerInfo"]//ul//li[4]//a')[0].get("href")
    Log("dvdPageLink: " + dvdPageLink)
    dvdPageElements = HTML.ElementFromURL(dvdPageLink)

    #
    valid_names = list()
    metadata.posters.validate_keys(valid_names)
    metadata.art.validate_keys(valid_names)

    # DVD Cover as first poster
    posterNum = 1
    try:
        dvdPosterURL = dvdPageElements.xpath('//div[@class="dvdcover"]//img')[0].get("src")
        if dvdPosterURL == None:
            dvdPosterURL = dvdPageElements.xpath('//div[@class="dvdcover"]//img')[0].get("data-src")
        metadata.posters[dvdPosterURL] = Proxy.Preview(HTTP.Request(dvdPosterURL, headers={'Referer': 'http://www.google.com'}).content, sort_order = posterNum)
        posterNum += 1
    except:
        Log("DVD Cover not found")


    # Background
    bgNum = 1
    try:
        background = detailsPageElements.xpath('//span[@id="trailer_thumb"]//img')[0].get('src')
        if background != None:
            Log("BG DL: " + background)
            metadata.art[background] = Proxy.Preview(HTTP.Request(background, headers={'Referer': 'http://www.google.com'}).content, sort_order = bgNum)
            bgNum += 1
            # also possible poster
            metadata.posters[background] = Proxy.Preview(HTTP.Request(background, headers={'Referer': 'http://www.google.com'}).content, sort_order = posterNum)
            posterNum +=1
        else:
            Log("BG not found")
    except:
        pass

    # Genres
    movieGenres.clearGenres()
    genres = detailsPageElements.xpath('//div[@class="trailerInfo"]//ul//li[3]//a')
    if len(genres) > 0:
        for genreLink in genres:
            genreName = genreLink.text_content().lower()
            movieGenres.addGenre(genreName)
            Log("Tags added: " + genreName)

    # Actors
    movieActors.clearActors()
    actors = detailsPageElements.xpath('//div[@class="trailerInfo"]//ul//li//span[@class="tour_update_models"]//a')
    Log("Actors found: "+str(len(actors)))
    if len(actors) > 0:
        for actorLink in actors:
            actorName = str(actorLink.text_content().strip())
            actorPageURL = actorLink.get("href")
            actorPage = HTML.ElementFromURL(actorPageURL)
            actorPhotoURL = actorPage.xpath('//div[@class="modelPicture"]//img')[0].get("src")
            if actorPhotoURL == None:
                actorPhotoURL = actorPage.xpath('//div[@class="modelPicture"]//img')[0].get("data-src")
            movieActors.addActor(actorName,actorPhotoURL)
            # add actor image as possible poster
            try:
                if len(actors) < 3:
                    metadata.posters[actorPhotoURL] = Proxy.Preview(HTTP.Request(actorPhotoURL, headers={'Referer': 'http://www.google.com'}).content, sort_order = posterNum)
                    posterNum += 1
            except:
                pass

    # Release Date
        date_object = datetime.strptime(str(metadata.id).split("|")[2], '%Y-%m-%d')
        metadata.originally_available_at = date_object
        metadata.year = metadata.originally_available_at.year


    # DVD page only place with more thumbs
    for dvdThumb in dvdPageElements.xpath('//div[@class="dvdScenePic"]//img'):
        dvdThumbURL = dvdThumb.get("src")
        try:
            if dvdThumbURL == None:
                dvdThumbURL = dvdThumb.get("data-src")
            metadata.art[dvdThumbURL] = Proxy.Preview(HTTP.Request(dvdThumbURL, headers={'Referer': 'http://www.google.com'}).content, sort_order = bgNum)
            bgNum += 1
        except:
            pass

    return metadata
```

**Comment by claygoldfinch** [comment] 2019-06-10 19:49
@kamuk90 Thanks for the contribution! I'm out of town right now, but I'll test this out and add it to my open pull request on Wednesday.

**Closed** 2019-09-17 03:23 UTC
Labels: Site Change
