### ISSUE TITLE
Videos are added to a collection of the videos name.

### ISSUE THREAD

**Issue by ApplicationError** [PAhelper/PhoenixAdult.bundle#420] opened 2019-10-01 10:59 UTC
When I add new content, each video is tagged its own name as a collection in addition to being tagged with the site's collection. 

I don't see a logical reason why each video should be in its own collection. It requires the user to go into each of the collections (that only have 1 video) and remove that tag, then delete that empty collection.

**Comment by SgtBatten** [comment] 2019-10-01 12:12
Duplicate of #304 

Please share which sites

**Comment by ApplicationError** [comment] 2019-10-01 12:17
Sorry, I didn't know this would be a site specific item. I think I've seen this happen on all sites... but recently with HardX and EroticaX

**Comment by pedrolara-boop** [comment] 2019-10-04 16:43
The same happens to me. 
Here are some of the sites that I found this to happen:
-Girlsway
-XEmpire
-Fantasy Massage
-Jules Jordan
-LetsDoeIt
-DDF
-At least one from Brazzers

**Closed** 2019-10-08 07:10 UTC
