### ISSUE TITLE
DDF Network changed to Porn World

### ISSUE THREAD

**Issue by monkTertman** [PAhelper/PhoenixAdult.bundle#1038] opened 2020-09-16 17:37 UTC
## Description 

DDF Network has changed to Porn World.
Their previous website redirects to `https://pornworld.com/?source=ddfnetwork` now.

New website has a search feature as well.

**Comment by DirtyRacer1337** [comment] 2020-09-16 20:38
Duplicate of #661

**Closed by DirtyRacer1337** 2020-09-16 20:38 UTC
