### ISSUE TITLE
Emby/Jellyfin support 

### ISSUE THREAD

**Issue by mukalaaa** [PAhelper/PhoenixAdult.bundle#773] opened 2020-05-21 20:24 UTC
Your plugin is amazing and actually many of us went away from plex to Emby or Jellyfin because the developer does listen us the users unlike plex. The only reason myself and many others started using Plex again is your amazing plugin. great job guys!! really, this plugin is a life saver!!

Yet as you all know the community is moving away from Plex now because of the privacy issues and how unfriendly the developers are. it seems like an app that was designed with cooperates in mind not the users unlike other alternatives such as Emby and Jellyfin 

is there any way? or future plan to make this work with the other options? 
if it is matter of funding, I believe many of us will be more than happy to support you financially if you ever decide to make this work. 

As much as I loved Plex when I started organizing and streaming my media 6 or 7 years ago. as much as I cannot even stand it now because of the decisions made by its developers and how invasive they are to our privacy and  content.

Thanks a lot guys and keep up the good work 
cheers!

**Comment by DirtyRacer1337** [comment] 2020-05-21 21:06
Duplicate of #387

**Closed by DirtyRacer1337** 2020-05-21 21:06 UTC
