### ISSUE TITLE
HardX problem

### ISSUE THREAD

**Issue by fritz276** [PAhelper/PhoenixAdult.bundle#10] opened 2018-12-02 17:00 UTC
CRITICAL (agentkit:1078) - Exception in the update function of agent named 'PhoenixAdult', called with guid 'com.plexapp.agents.phoenixadult://_en_video_Super-Cute-Workout-Scene-01_131927|278?lang=en' (most recent call last):File "/usr/pbi/plexmediaserver-amd64/share/plexmediaserver/Resources/Plug-ins-9d51fdfaa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1076, in _update
    agent.update(obj, media, lang, **kwargs)
  File "/var/db/plexdata/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 496, in update
    metadata = PAsearchSites.siteHardX.update(metadata,siteID,movieGenres)
  File "/var/db/plexdata/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/siteHardX.py", line 45, in update
    tagline = detailsPageElements.xpath('//a[@class="dvdLink  "]')[0].get('title')
  File "/usr/pbi/plexmediaserver-amd64/share/plexmediaserver/Resources/Plug-ins-9d51fdfaa/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range

**Comment by PAhelper** [comment] 2018-12-03 15:44
This should be resolved now. I didn't have time to thoroughly test it though.

**Comment by PAhelper** [comment] 2018-12-03 21:35
It should be logging the bg and poster(s) URLs. Can you paste one of your examples? It should pull 1 BG URL and 4-5 Poster URLs per match...

When I very briefly tested on my example file while coding this morning, the URLs were proper in the logs and loaded the image when I pasted them back into a browser, but they were not being saved to my Plex Server, and I'm unsure why. My best guess at this point is the referrer maybe?

**Comment by PAhelper** [comment] 2018-12-06 15:33
Duplicate of #12

**Closed by PAhelper** 2018-12-06 15:33 UTC
Labels: bug
