### ISSUE TITLE
[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE]

### ISSUE THREAD

**Issue by mutluerol** [PAhelper/PhoenixAdult.bundle#44] opened 2019-01-07 23:35 UTC
sitePornPros has error with ssl

**Comment by mutluerol** [comment] 2019-01-08 10:09
in my PMS Plugin Logs, ifound ;
URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>

**Comment by PAhelper** [comment] 2019-01-08 20:09
Duplicate of #13

**Closed by PAhelper** 2019-01-08 20:09 UTC
