### ISSUE TITLE
sometimes pervmom pulling wrong metadata even when the name appear correct with exact match

### ISSUE THREAD

**Issue by xmxier** [PAhelper/PhoenixAdult.bundle#222] opened 2019-06-15 12:16 UTC
sometimes pervmom pulling wrong metadata even when the name appear correct with exact match?

**Comment by claygoldfinch** [comment] 2019-06-15 14:15
Have any examples? Search term & log file?

**Comment by xmxier** [comment] 2019-06-15 15:33
just now tried to match /899/welcum-home-stepmom/aaliyah-love2
it ends up matching Unclasp Her Stepmom Cooch with different pictures for the scene and the actress.

**Comment by xmxier** [comment] 2019-06-15 15:36
and every time I try to refresh metadata it ends up with new wrong thumbnail.

**Comment by claygoldfinch** [comment] 2019-06-15 17:47
Thanks!

This was caused by a commit I made a couple weeks back (1b32c15), sorry bout that. Should be totally resolved in PR #219. PR also fixes an issue with the actress for that scene. Let me know if you run into any other issues with scenes/actresses, I don't have a large PervMom collection to test with.

**Closed** 2019-06-16 00:46 UTC
