### ISSUE TITLE
Tonights Girlfriend

### ISSUE THREAD

**Issue by stevef9432203** [PAhelper/PhoenixAdult.bundle#1580] opened 2022-08-03 22:30 UTC
**Describe the bug**
Tonights Girlfriend 
never matches

Never matches
**Include**
1. Scene URL
2. https://www.tonightsgirlfriend.com/scene/brooklyn-chase-oils-her-tits-up-25628?&custom1=17581
3. File Name
4. TonightsGirlfriend - 19-10-04 - Brooklyn Chase - XXX 2160p.mp4
5. Log File
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/9255378/com.plexapp.agents.phoenixadult.log)

**Comment by 11samype** [comment] 2022-08-07 01:43
Duplicate of #1562

**Closed** 2022-08-07 10:33 UTC
